In [14]:
import numpy as np

In [29]:
# random matrix
a=int(input())
b=int(input())
A=np.random.rand(a,b)
print(A)

100
99
[[0.9766754  0.69430288 0.46757203 ... 0.85000129 0.35772997 0.31848491]
 [0.40465868 0.96003701 0.60271889 ... 0.69390822 0.70990589 0.03900518]
 [0.72735074 0.2170049  0.95282681 ... 0.21429338 0.87827359 0.62318293]
 ...
 [0.79467935 0.82146856 0.7325471  ... 0.46872547 0.54726046 0.01963051]
 [0.24914376 0.54654432 0.62135363 ... 0.98387427 0.16347096 0.81585192]
 [0.41909604 0.58061423 0.41559215 ... 0.15777042 0.75341691 0.13579368]]


In [30]:
#SVD
U,S,Vt=np.linalg.svd(A)
print('U \n',U)
print('sigma \n',S)
print('V tau \n',Vt)

U 
 [[-0.10184023 -0.03854921  0.12873939 ... -0.13184147  0.09206613
  -0.27459984]
 [-0.10309482 -0.10062814 -0.08234635 ... -0.10216979  0.1109048
   0.10336711]
 [-0.10482017 -0.0412345   0.09296599 ...  0.0313151   0.06851515
  -0.02894179]
 ...
 [-0.10076998 -0.1191572  -0.10111973 ... -0.13053357  0.1161502
  -0.02342661]
 [-0.09237221 -0.10013815 -0.03410747 ...  0.03008254  0.04890837
   0.16703997]
 [-0.09885599  0.05774468  0.0089547  ...  0.08438119 -0.11659356
  -0.05427315]]
sigma 
 [4.99724375e+01 5.58865503e+00 5.52780348e+00 5.28246666e+00
 5.19465875e+00 5.06327186e+00 4.92515326e+00 4.84757608e+00
 4.81456078e+00 4.68678490e+00 4.59011086e+00 4.51402305e+00
 4.47357146e+00 4.38271234e+00 4.33606017e+00 4.27507877e+00
 4.18704842e+00 4.17357036e+00 4.10688124e+00 4.04474002e+00
 3.98884719e+00 3.91780577e+00 3.82771685e+00 3.74793677e+00
 3.67924788e+00 3.62520006e+00 3.56494879e+00 3.51941718e+00
 3.43713421e+00 3.41330742e+00 3.34757041e+00 3.29079357e+00
 3.2360180

In [32]:
#복원
Sm=np.zeros((a,b))
for i in range(min(a,b)):
    Sm[i][i]=S[i]
A_after=np.dot(np.dot(U,Sm),Vt)
print(A_after)

[[0.9766754  0.69430288 0.46757203 ... 0.85000129 0.35772997 0.31848491]
 [0.40465868 0.96003701 0.60271889 ... 0.69390822 0.70990589 0.03900518]
 [0.72735074 0.2170049  0.95282681 ... 0.21429338 0.87827359 0.62318293]
 ...
 [0.79467935 0.82146856 0.7325471  ... 0.46872547 0.54726046 0.01963051]
 [0.24914376 0.54654432 0.62135363 ... 0.98387427 0.16347096 0.81585192]
 [0.41909604 0.58061423 0.41559215 ... 0.15777042 0.75341691 0.13579368]]
